# Dockerfile for general node-based API server

FROM node:10

LABEL version="1.0"
LABEL maintainer="Ryan Robillard github.com/rrobilla"
LABEL description="This is a general purpose node server image setup to serve a REST API as a base to work off"

